<?php
// $Id$

/**
 * @file
 * Implements necessary callbacks for Calendar Framework administration forms.
 */

/**
 * Form callback for listing all available calendars and their configs.
 *
 * @return
 *   An array of form elements.
 *
 * @ingroup forms
 */
function calendar_framework_calendars_form() {

}

/**
 * Form callback for a calendar admin settings.
 *
 * @param $identifier
 *   Calendar identifier.
 *
 * @return
 *   An array of form elements.
 *
 * @ingroup forms
 */
function calendar_framework_calendar_form(&$form_state, $identifier) {

}
