<?php
// $Id$

/**
 * @file
 * Implements necessary hooks for Multical module, plus API and helper functions.
 */

/**
 * Implements hook_perm().
 */
function multical_perm() {

}
 
/**
 * Implements hook_init().
 */
function multical_init() {

}

/**
 * Implements hook_menu().
 */
function multical_menu() {

}

/**
 * Implements hook_patch().
 */
function multical_patch() {

}

/**
 * The heart of API, which somehow acts as a ExtDateTime procedural factory wrapper.
 *
 * The function as the heart of the API instantiate the proper object 
 * corresponding to the passed calendar identifier or the default one.
 *
 * @param $calendar
 *   Calendar identifier.
 *
 * @return
 *   The instantiated calendar object.
 */
function multical($calendar = NULL) {

}

/**
 * API function to provide a list of all calendars.
 *
 * @param $op
 *   Requests the calendar list format.
 */
function multical_calendars() {

}

/**
 * Helper function to collect a list of defined calendars.
 *
 * @return
 *   An array of available calendars.
 */
function _multical_calendars_build() {
  $calendars = array();
  
  $calendars_defined = module_invoke_all('calendar_info');
  foreach ($calendars_defined as $identifier => $info) {
    $info['config'] = variable_get('multical_' . $identifier . '_settings');
    $calendars[$identifier] = $info;
  }
  
  return $calendars;
}

/**
 * API function to get current default calendar.
 *
 * @return
 *   An array of default calendar information.
 */
function multical_default_calendar() {

}

