<?php
// $Id$

/**
 * @file
 * Implements necessary hooks of Calendar Framework module, to support Jalali Calendar.
 */

/**
 * Implements hook_calendar_info().
 */
function calendar_jalali_calendar_info() {
  $calendar = array();

  $calendar['jalali'] = array(
    'name' => t('Jalali (Solar Hijri)'),
    'format callback' => 'calendar_jalali_formatter',
    'convert callback' => 'calendar_jalali_converter',
    'config callback' => 'calendar_jalali_admin_form',
  );

  return $calendar;
}


/**
 * Form callback for Jalali calendar administration.
 *
 * @param $config
 *   Calendar specific config options.
 *
 * @todo IMPLEMENT!
 */
function calendar_jalali_admin_form($config) {
  $form = array();

  // Test.
  $form['calendar_jalali_test'] = array(
    '#type' => 'checkbox',
    '#title' => t('This is a test calendar specific option.'),
    '#default_value' => $config['calendar_jalali_test'],
    '#return_value' => 1,
  );

  return $form;
}

/**
 * Validation callback for Jalali calendar administration form.
 *
 * @todo IMPLEMENT!
 */
function calendar_jalali_admin_form_validate($form, &$form_state) {
  // Test.
  if ($form_state['values']['calendar_jalali_test']) {
    drupal_set_message(t('love that checkbox? :)'));
  }
}


/**
 * Jalali calendar date formatter callback.
 *
 * @param $timestamp
 *   Unix timestamp to be formatted. 
 *   The proper timezone value has been added by the native format_date().
 * @param $type
 *   The format to use. Can be "small", "medium" or "large" for the preconfigured
 *   date formats. If "custom" is specified, then $format is required as well.
 * @param $format
 *   PHP date() function format string.
 * @param $langcode
 *   Optional language code to translate to a language other than the default.
 * @param $calendar
 *   A copy of calendar information.
 *
 * @return
 *   The formatted date or FALSE otherwise.
 *
 * @see format_date()
 */
function calendar_jalali_formatter($timestamp, $type, $format, $langcode, $calendar) {
  // TODO: Implement!
  return FALSE;
}


/**
 * Jalali calendar date converter callback.
 *
 * @todo IMPLEMENT!
 */
function calendar_jalali_converter() {
  return FALSE;
}

